# Generated by Django 5.2.6 on 2025-09-17 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postel_code',
            new_name='postal_code',
        ),
    ]
